services:
  app:
    image: ghcr.io/brahima-fofana/nsiago-assur-backend:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - shared-network
      -
networks:
  shared-network:
    external: true